{{- if .Values.env.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sbiMQ.resourceFullname" (list . "env") }}
  labels:
    {{- include "sbiMQ.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.env.secret }}
  {{- $key | nindent 2 }}: {{ b64enc $value }}
{{- end }}
{{- end }}
